### PR TITLE
Planets Tab (monitor will come later)

### PR DESCRIPTION
**Pull request by MaketendoDev**

### CODE REVIEW

**Comment by MaketendoDev** [comment]
image

**Review by Duzos — CHANGES_REQUESTED** [review]
did you run `./gradlew spotlessApply` ?

**Comment by MaketendoDev** [comment]
crap not yet I'll do it now do I need to do this every time I do front end changes?

**Comment by Duzos** [comment]
everytime you change anything

**Comment by Duzos** [comment]
lmk when u do it

**Comment by MaketendoDev** [comment]
huh? i'm confused I spotless applied it?

**Comment by Duzos** [comment]
yeah i think its my check being broken

**Pull request merged**
