### PR TITLE
Updated Snowy Biome Texture

### PR DESCRIPTION
**Pull request by MaketendoDev**
From IDEA #428 By… themilksnatcher *sigh*

### CODE REVIEW

**Comment by Duzos** [comment]
closes 
#428 
#427

**Review by Duzos — APPROVED** [review]
LGTM
just perform spotlessApply before merge

**Comment by MaketendoDev** [comment]
Alr will do leme add one more commit to this from them and then I’ll run the spotless apply

**Comment by MaketendoDev** [comment]
dunit
and

**Comment by MaketendoDev** [comment]
#430

**Comment by MaketendoDev** [comment]
closes #430

**Pull request merged**
